# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientsiezures',
            old_name='current_GPS',
            new_name='siezure_GPS',
        ),
    ]
